### ISSUE TITLE
[FEAT] Add information about which check failed in CommandCheckFailure

### ISSUE THREAD

**Issue by LordOfPolls** [NAFTeam/NAFF#206]
**Is your feature request related to a problem? Please describe.**
> Checks are actually useless as is.
There's no way to get information about which check failed if a command has multiple, and no useful information comes out of them for the sake of error messages

**Describe the solution you'd like**
Add information about which check failed, and possibly why to `CommandCheckFailure`

**Describe alternatives you've considered**
N/A

**Additional information**
N/A

**Comment by artem30801** [comment]
Can checks user code raise an error? If so, both check name (or check object entirely?) and user-raised exception could be stored in CommandCheckFailure attributes

**Comment by LordOfPolls** [comment]
That's fine by me

**Comment by LordOfPolls** [comment]
Im unsure on what structure this data should be communicated. Just a string with the check's method name?

**Comment by AstreaTSS** [comment]
Is it possible to send the whole function? Who knows, maybe someone will have two checks named the same thing.

If not, the name would be the best way to do it.

**Comment by LordOfPolls** [comment]
it apparently already was, and according to git-blame it has been there since the `CommandCheckFailure` class was created
![image](https://user-images.githubusercontent.com/22540825/162393317-3c88f42e-f4ce-4230-8d5c-f87f38b37b87.png)

**Comment by LordOfPolls** [comment]
Closing this issue as per the above
