### ISSUE TITLE
[BUG] str(emoji) returns the wrong format

### ISSUE THREAD

**Issue by deadkex** [NAFTeam/NAFF#211]
**Describe the bug**
str(emoji) gives <:👋:None> when it is a standard emoji

**To Reproduce**
```
@listen()
async def on_message_reaction_add(event: MessageReactionAdd):
    str(event.emoji)
```

**Expected behaviour**
It should return the emoji in a format thats actually usable on discord

**Additional information**
I am on latest dev.
Discussion can be seen in thread [here](https://discord.com/channels/870046872864165888/932642512907169813/934130698883842079)

**Comment by leestarb** [comment]
Thanks for the report, issue resolved in #212
