### ISSUE TITLE
[FEAT] ext.Task.create should work on Scale methods

### ISSUE THREAD

**Issue by artem30801** [NAFTeam/NAFF#240]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when `ext.Task.create(...)` doesn't work on methods in Scales

**Describe the solution you'd like**
`ext.Task.create(...)` works on methods in Scales

**Describe alternatives you've considered**
Register scale methods as tasks out of the class (in setup function). It's ugly.

**Additional information**
Polls pls

**Comment by LordOfPolls** [comment]
As per #contributors. Start your tasks in `on_startup` rather than `__init__`. This will however, be fixed
