### ISSUE TITLE
[FEAT] Use Bluenix2's discord-typings to better type the dicts that come out of HTTP requests

### ISSUE THREAD

**Issue by silasary** [NAFTeam/NAFF#249]
It's a whole bunch of TypedDicts that let static type checkers better know the contents of the HTTP responses

https://pypi.org/project/discord-typings/

Definitely a nice-to-have

**Comment by Bluenix2** [comment]
There has not been a release since December last year, but I was planning on making another release soon once I have most endpoint-specific payloads Discord uses typed.

I can definitely pick up a quicker release schedule if this starts being used.

**Comment by LordOfPolls** [comment]
Assuming blue updates their repo, im on board with this

**Comment by Bluenix2** [comment]
[Version 0.2.2](https://github.com/Bluenix2/discord-typings/releases/tag/v0.2.2) has now been [published on PyPI](https://pypi.org/project/discord-typings/0.2.2/) with everything from the repository.
