### ISSUE TITLE
[BUG] User.mutual_guilds is broken

### ISSUE THREAD

**Issue by Kigstn** [NAFTeam/NAFF#262]
**Describe the bug**
User.mutual_guilds is broken since User.user_guilds does not exist

**To Reproduce**
The code you used to produce this bug, must be in a code-block:
Try to use User.mutual_guilds

**Expected behaviour**
A list of mutual guilds

**Additional information**
Any other information about the problem.
Too tired to fix myself, this also looks like it may be annoying to fix

**Comment by LordOfPolls** [comment]
Fixed in c212ade997bbeca33a30605b4498131c5183c19c
