### ISSUE TITLE
[FEAT] Add Modal Interactions

### ISSUE THREAD

**Issue by zevaryx** [NAFTeam/NAFF#263]
**Is your feature request related to a problem? Please describe.**
As of today, Modal Interactions are official. An announcement was made in the Discord Developers server today.

**Describe the solution you'd like**
An implementation of Modal Interactions

**Describe alternatives you've considered**
None

**Additional information**
See https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-modal

**Comment by Wolfhound905** [comment]
#186
