### ISSUE TITLE
[FEAT] Application Command Attachment Option Types

### ISSUE THREAD

**Issue by zevaryx** [NAFTeam/NAFF#264]
**Is your feature request related to a problem? Please describe.**
As of today, Application Command Attachment Options Types are official. An announcement was made in the Discord Developers server today.

**Describe the solution you'd like**
An implementation of Application Command Attachment Options Types

**Describe alternatives you've considered**
None

**Additional information**
See https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type

**Comment by leestarb** [comment]
Added in #265
