### ISSUE TITLE
[BUG] Component response is not emphemeral

### ISSUE THREAD

**Issue by Kigstn** [NAFTeam/NAFF#269]
**Describe the bug**
`ephemeral=True` is passed and the message flag is set, yet the message is not hidden. 
![image](https://user-images.githubusercontent.com/38250010/153233847-7266af19-66fb-4609-91e4-f5113eb3892b.png)
![image](https://user-images.githubusercontent.com/38250010/153233899-33c5e186-753b-464d-8f50-55d3c8882988.png)

**To Reproduce**
The code you used to produce this bug, must be in a code-block:
Respond to a `ComponentContext` with `ctx.send("stuff", **ephemeral=True)`**

**Expected behaviour**
A hidden message appears

**Additional information**
Any other information about the problem.

**Comment by LordOfPolls** [comment]
I cannot replicate this. Check you're not using `AutoDefer`

![image](https://user-images.githubusercontent.com/22540825/153558375-29c54c06-9b75-4409-83d5-55e4c311d133.png)
Code used:
```python
@message_command()
async def send_button(ctx: MessageContext):
    await ctx.send("Test Button", components=Button(1, "Test Button", custom_id="Test1"))


@component_callback("Test1")
async def test_button_callback(ctx: ComponentContext):
    await ctx.send("stuff", ephemeral=True)
```

**Comment by benwoo1110** [comment]
@Kigstn I think it will be good if you can show the full code used to reproduce this issue.

**Comment by Kigstn** [comment]
Forgot to close this. Was my bad, I did not defer with ephemeral=True
