### ISSUE TITLE
[FEAT] Allow Multiple Bot Instances In The Same Process

### ISSUE THREAD

**Issue by KAJdev** [NAFTeam/NAFF#290]
**Is your feature request related to a problem? Please describe.**
When creating multiple bot instances, only one continues to send heartbeats and remain active.

**Describe the solution you'd like**
The best solution would be the ability to create as many instances of Snake, and use login() in a task to have them all connect separately.

**Describe alternatives you've considered**
The alternatives all would require creating separate processes and using pipes or IPC to communicate between instances which is extreme pain.

**Comment by i0bs** [comment]
Is there any prio status on this, or labeling? I'm currently having issues making this work as well, there's only one main heartbeater and other instantiations of the client fail to create others respectively. Adding a `__new__` magic for this would be very convenient with IPC-based solutions.

**Comment by LordOfPolls** [comment]
So, it can be done without to much pain, the downside is there isnt a public method to make it work. Please excuse the ugly test code

```python
tokens = [...]
bots = []

for token in tokens:
    _bot = Snake()
    bots.append(_bot)
    print(f"Logging in with {token}")
    loop.run_until_complete(_bot.login(token))
    print(_bot.user.username)


print(f"Attempting to start {len(bots)} gateways")
loop.run_until_complete(asyncio.gather(*[b.start_gateway() for b in bots]))
```
This will create n number of bots and connect them all, however the issue arrises that the bot instances attempt to *own* listeners, meaning one bot will get all events. In real terms this means if you run a command, one bot will respond twice, meanwhile the other bot wont do anything, this is fixable, but not ideal.

**Comment by KAJdev** [comment]
could this be sorta monkey-patched by not using @listen() decorators and manually registering them?

**Comment by silasary** [comment]
> bot instances attempt to own listeners, meaning one bot will get all events. 

Reading the code, I'm not convinced this is accurate.

> by not using @listen() decorators and manually registering them?

You'd need to convert them into listeners to register them anyway.

**Comment by LordOfPolls** [comment]
@silasary 
> Reading the code, I'm not convinced this is accurate.

My theory to the cause was based on the wrapping process. The library literally wraps objects and uses the current client as a param. Figuratively owning the object.

I believe there are other issues resulting in the behaviour I've found, but I've yet to have time to debug further so I reported what I had found so far.

End of the day the lib wasn't written with multi-instancing in mind, so a few changes are required. Shouldn't be too bad, just annoying

But either way we spin it, more testing is needed to determine the cause of the behaviour. As I'll admit, I'm theorising

**Comment by KAJdev** [comment]
Any movement on this?

**Comment by silasary** [comment]
Currently waiting on #346 before more progress can be made here

**Comment by LordOfPolls** [comment]
We are now working on this... it is suffering incarnate
