### ISSUE TITLE
[BUG] Inconsistent fetch_* function behaviour

### ISSUE THREAD

**Issue by Kigstn** [NAFTeam/NAFF#323]
**Describe the bug**
Not all .fetch_* instances return None optionally. Some raise not found errors. 

Someone needs to go through all methods and make sure the NotFound exception is caught and None is returned everywhere. Currently it's 50/50

This is needed everywhere
```py
        try:
            return await self.cache.fetch_member(guild_id, user_id)
        except NotFound:
            return None 
```

**Comment by benwoo1110** [comment]
https://github.com/Discord-Snake-Pit/Dis-Snek/blob/07cf9445daaebb4b122744c91b1a8236a21269d9/dis_snek/models/discord/guild.py#L1300-L1315
hmm should `fetch_ban` return None?
