### ISSUE TITLE
[BUG] msg.channel_mentions can and will be None

### ISSUE THREAD

**Issue by LordOfPolls** [NAFTeam/NAFF#324]
**Describe the bug**
Discord will only populate the `channel_mentions` key of a message if `textual channels that are visible to everyone in a lurkable guild` are in the message. Obviously this isnt ideal and causes confusion as channels are clearly mentioned, but not available in the message object. 

Also the default value of `message.channel_mentions` is None, it should be []

Categorised as a `bug` as this is not user-expected behaviour, however it could be argued that its api-expected behaviour

**To Reproduce**
If you have acceess to the test guild, look here: https://canary.discord.com/channels/701347683591389185/945763271384891424/945936910793199666

Otherwise, send a message mentioning a channel **not** everyone can see. 

**Expected behaviour**
All channels mentioned and known by the bot are in this list

**Comment by AstreaTSS** [comment]
Theoretically, you could do this with a simple regex. It wouldn't be 1:1 with the API, but it *would* be more expected behavior.
