### ISSUE TITLE
[FEAT] Callback decorator (and related things) for modals

### ISSUE THREAD

**Issue by artem30801** [NAFTeam/NAFF#391]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when no callback decorator for modals. In some cases it allows for cleaner code than usage of `wait_for_modal`

**Describe the solution you'd like**
Modals should have the same persistent callback system we use for components, including callback decorators.

**Comment by benwoo1110** [comment]
Should we have a common callback decorator for both component and modal, or separate?

**Comment by LordOfPolls** [comment]
Imo separate is better UX
