### ISSUE TITLE
[FEAT] Port Sentry integration from taipan to main library

### ISSUE THREAD

**Issue by silasary** [NAFTeam/NAFF#403]
This is relatively easy, I'm just waiting for Voice to get merged before I do it.

**Comment by Wolfhound905** [comment]
@silasary hey is there any update on this?

**Comment by artem30801** [comment]
In my opinion, all external integrations should not be in this repo (even in ext), but instead be placed in separate repos under the same org, to be optional dependencies

**Comment by silasary** [comment]
I've been thinking about that, and I'm very torn.  Having stuff in external repos reduces discoverability, and makes the features a lot less likely to be used.

`naff_audio` must be separate for messy reasons, but for most extensions, I'd rather them be relatively painless and selling points for the library, rather than hidden, generally unknown 2nd-party plugins.

Where possible, I'd much rather have them shipped in `ext`, and have any additional dependencies locked behind an extra, rather than "This [really cool feature](https://github.com/artem30801/nafftrack) exists, but you'd never know it unless you happened to be looking at Discord the one day a year someone brings it up"

**Comment by compil3** [comment]
I would definitely use if it were shipped with the library, I already do but having less things to manually configure that are quality of life improvements, in my eyes are well worth it.
