### ISSUE TITLE
[BUG] `GuildVoice.position` is not working as it should

### ISSUE THREAD

**Issue by Kigstn** [NAFTeam/NAFF#523]
**Describe the bug**
`GuildVoice.position` is not working as it should

**To Reproduce**
Look at a category channel and compare the positions of the channels. Voice channels are not ordered, text channels are ordered correctly, but start at `position = 2` instead of 0/1.

**Expected behaviour**
`GuildVoice.position` reflects the position on discord

**Additional information**
[Discord Link](https://canary.discord.com/channels/870046872864165888/893158404237979688/982194216526561292)

![image](https://user-images.githubusercontent.com/38250010/172852272-7a1db10d-e36c-49d9-b042-6b5ee3234d41.png)
![image](https://user-images.githubusercontent.com/38250010/172852289-25eb7b19-b92b-4bda-b2d7-5ee7fd43fa61.png)
![image](https://user-images.githubusercontent.com/38250010/172852359-c5a0a771-93a2-4210-be72-c26252a7a9c5.png)
![image](https://user-images.githubusercontent.com/38250010/172852370-9a1f7a14-b3f6-4296-9275-98a41e80f74b.png)
![image](https://user-images.githubusercontent.com/38250010/172852382-6a5447ea-db7f-4fc2-909b-ee62c265d82c.png)
![image](https://user-images.githubusercontent.com/38250010/172852392-5348db5a-2f84-4f7a-ba0c-144f1ea2bc7f.png)

**Comment by LordOfPolls** [comment]
Testing suggest this is an issue on discords end, not ours. 

![image](https://user-images.githubusercontent.com/22540825/176998048-74199c02-f99b-443e-80e1-ced4cdcaa68c.png)
![image](https://user-images.githubusercontent.com/22540825/176998051-6f771505-946d-413a-a674-ae7aa3e1eadf.png)

**Comment by Kigstn** [comment]
Reported to discord (https://github.com/discord/discord-api-docs/issues/5147)

Seems like the position not starting with 0 is intended however, since positions are on a server and channel type basic.
