### ISSUE TITLE
[BUG] Command Syncing 

### ISSUE THREAD

**Issue by Wolfhound905** [NAFTeam/NAFF#557]
### NAFF Version

any

### Describe the Bug

When using slash command options max and mins and you change just `max_value` or others the command does not sync

### Expected Results

The command should sync with the new min_value

### Minimal Reproducible Code

```python
@naff.slash_command("int")
@naff.slash_option(
    "int",
    "test",
    naff.OptionTypes.INTEGER,
    min_value=0,
    max_value=15, # Just change this value and command wont sync
)
async def test(ctx, string):
    await ctx.send(string)
    return "test"
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LordOfPolls** [comment]
The attribute needs adding to this dict https://github.com/NAFTeam/NAFF/blob/master/naff/models/naff/application_commands.py#L1013-L1021

Either you can add it or i'll add it tonight
