### ISSUE TITLE
[FEAT] Add Thread Support for Components

### ISSUE THREAD

**Issue by xCraith** [NAFTeam/NAFF#597]
### Is your feature request related to a problem? Please describe.

The problem is that it is currently not possible via NAFF to lock or archive threads via components, something which I personally would really appreciate. And since I heard that it is available in the API i'd really appreciate to have that feature in NAFF.

https://didnt-ask.de/wm6xXrEr <-- Screenshot.

Basically I press on a button and the Thread should be locked, which currently is not possible to do.

### Describe the solution you'd like

As said above. I want when I use components to be able to lock or archive or generally manage threads.

**Comment by LordOfPolls** [comment]
Correction to this issue

The issue is that naff doesnt have a `message.thread` attribute. Not an issue with components
