### ISSUE TITLE
[FEAT] Add .bot to the Event class

### ISSUE THREAD

**Issue by Kigstn** [NAFTeam/NAFF#86]
( Rewriting that here so it's not forgotten :) )

**Is your feature request related to a problem? Please describe.**
Accessing the client obj in events in separate files is a pita.

**Describe the solution you'd like**
Add .bot to all events, namely the BaseEvent class.

**Describe alternatives you've considered**
Get the protected client obj from for example Member works (Member._client)

**Additional information**
/

**Comment by Kigstn** [comment]
I would do it myself, but the dispatching logic is very confusing and idk where to add it

**Comment by LordOfPolls** [comment]
I've added this to my gateway/dispatch overhaul, as this makes the most sense there
